---
title: "Visualizadores de datos sociales en R"
author: "Bastián Olea Herrera"
format:
  html:
    link-external-icon: false
    include-in-header:
      text: |
        <link rel="shortcut icon" type="image/png" href="apple-touch-icon.png">
        <link rel="icon" type="image/x-icon" href="favicon.ico">
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">

---

```{r setup}
#| echo: false
#| warning: false

library(shiny)
library(glue)
library(colorspace)
library(htmltools)

source("funciones.R")
source("colores.R")
```


```{r css}
#| echo: false
#| warning: false
#| output: asis

fluidPage(lang = "es",
          
          #titulo y autor (entregados por yaml de quarto)
          tag_css("h1.title, .title.h1 { margin: 24px; margin-top: 24px; margin-left: 30px; color: {{color_enlaces}}; }
                  
                  .quarto-title-meta-heading { display: none; }
                  
                  .quarto-title-meta-contents {
                  margin-left: 30px; margin-top: 6px; margin-bottom: 12px; color: {{color_texto}};"),
          
              # color hover toolbar
    tags$style(HTML(".navbar-brand:hover, .nav-link:hover, .quarto-navigation-tool:hover, .navbar-brand:focus {color:", color_texto, " !important; }")),
          
              # colores de la animación de fondo
      tags$style(HTML("@keyframes pulse {
  from {background-color:", color_destacado_2, ";}
  to {background-color:", color_destacado, ";} }")),
  
          #favicon
          tags$head(
            tags$link(rel = "shortcut icon", href = "www/favicon.ico"),
            tags$link(rel = "apple-touch-icon", sizes = "180x180", href = "apple-touch-icon.png"),
            tags$link(rel = "icon", type = "image/png", sizes = "32x32", href = "www/favicon-32x32.png"),
            tags$link(rel = "icon", type = "image/png", sizes = "16x16", href = "www/favicon-16x16.png")
          ),
          
          tag_css("body {
             background-color: {{color_fondo}};}
             
             a {
             color: {{color_enlaces}};
             }
           
             a:hover {
             color: #724be7;
             text-decoration: none !important; }
             
             h1{
             color: {{color_texto}};}
             
             .icono:hover {
             filter: brightness(130%); transition: 0.4s}
             
             .icono_claro:hover {
             filter: brightness(90%) saturate(140%); transition: 0.4s}")
)
```


```{r header}
#| echo: false
#| warning: false
#| output: asis

fluidPage(lang = "es",
          fluidRow(
            column(12, 
                   style = css(font_size = "110%", color = color_texto, 
                               margin_left = "30px", margin_right = "30px", margin_bottom = "-8px"),
                   
                   #subtítulo ----     
                   div(style = "height: 16px;"),
                   
                   cuadro_intro(
                     markdown("Portafolio de aplicaciones web interactivas sobre datos sociales, diseñadas y programadas en R por [Bastián Olea Herrera](https://bastianolea.rbind.io), sociólogx (U. Alberto Hurtado) y magíster en sociología (U. Católica de Chile)."),
                   ),
                   
                   # intro ----
                   div(style = "height: 20px;"),
                   
                   markdown("Este portafolio contiene **aplicaciones web para la visualización y análisis de datos sociales**, con un interés por la facilidad de uso, la exploración y el pensamiento crítico."),
                   
                   markdown("El objetivo de estas apps es **transparentar datos sociales de forma atractiva y sencilla**, para que cualquier persona pueda responder sus inquietudes y explorar a partir de los datos."),
                   
                   markdown("Puedes encontrar [más información sobre las aplicaciones en mi sitio web](https://bastianolea.rbind.io/apps/).")
            ),
            
            # # aviso ----
            # cuadro_aviso(
            #   markdown("¿Quieres **aprender R** o aprender a desarrollar apps con R? [¡Contáctame!](https://bastianolea.rbind.io/contact) Ofrezco clases particulares de R, asesorías, desarrollo de apps, y apoyo para cualquier tipo de proyecto.")
            #        )
          )
)
```


```{r apps}
#| echo: false
#| output: asis

div(style = "overflow-y: hidden; ",
    tags$style(paste(".anchorjs-link {display:none}")), #ocultar icono de links
    
     # h3("Aplicaciones interactivas de datos sociales", 
     #   style = css(color = color_texto, 
     #               text_align = "center")),
    
    
    # palestina ----
    caja_app(titulo = "Genocidio en Palestina",
             texto = div(
               markdown("Visualizador de datos que busca reflejar el horror de la guerra y el exterminio que se están llevando a cabo en el territorio palestino por obra de Israel y sus aliados. Los datos provienen de Palestine Datasets y de Armed Conflict Location & Event Data, organizaciones que están documentando datos sobre identificación de víctimas y registro de sucesos de relevancia política en la región."),
               ),
             enlace = "https://bastianoleah.shinyapps.io/palestina/",
             colores = colores$palestina,
             imagen = "www/palestina.png", estilo_imagen = "height: 190px; margin: 22px; margin-bottom: 8px; margin-top: -15px;",
             colores_claros = FALSE
    ),
    
    
    
    # temperatura ----
    caja_app(titulo = "Temperaturas extremas en Chile",
             texto = div(
               markdown("Visualización de datos de temperaturas extremas en el país. Permite consultar rápidamente datos históricos para obtener gráficos que revelan los cambios en temperaturas a través del tiempo en nuestro país. El objetivo es visibilizar los efectos del cambio climático por medio de los datos."),
               markdown("Los datos son obtenidos desde fuentes oficiales, y abarcan aproximadamente desde 1970 a 2024.")),
             enlace = "https://bastianoleah.shinyapps.io/temperaturas_chile/",
             colores = colores$temperaturas,
             imagen = "www/temperaturas_chile.png", estilo_imagen = "height: 190px; margin: 22px; margin-bottom: 2px; margin-top: 0px;",
             colores_claros = FALSE
    ),
    
    
    
    # prensa ----
    caja_app(titulo = "Análisis de prensa de Chile",
             texto = div(
               markdown("Aplicación de **análisis de texto** de prensa escrita chilena. Contiene varios gráficos que cuantifican el contenido de las noticias de Chile, semana por semana. Los gráficos permiten identificar qué palabras son las más usadas a través del tiempo, lo cual a su vez revela cómo va variando el acontecer nacional."),
               markdown("Los datos de esta aplicación son obtenidos mediante web scraping de forma diaria, pero la app se actualiza semanalmente. La base de datos comprende más de **600 mil noticias**, que suman más de 100 millones de palabras, abarcando más de 21 fuentes periodísticas distintas.")),
             enlace = "https://bastianoleah.shinyapps.io/prensa_chile/",
             colores = colores$prensa,
             imagen = "www/prensa_chile.png", estilo_imagen = "height: 170px; margin: 22px; margin-bottom: 8px; margin-top: -8px;",
             colores_claros = TRUE
    ),
    
    
    # economía ----
    caja_app(titulo = "Indicadores económicos Chile",
             texto = div(p("Tablero que presenta ", strong("+8 indicadores económicos del Banco Central de Chile,"), "cuya presentación resumida permite analizar la situación económica del país."),
                         p("Los datos de esta aplicación son obtenidos de forma automática dos veces al día, garantizando que se encuentren actualizados. Además, la arquitectura de esta app facilita el proceso de añadir nuevos indicadores.")),
             enlace = "https://bastianoleah.shinyapps.io/economia_chile/",
             colores = colores$economia,
             imagen = "www/economia_chile.png", estilo_imagen = "height: 150px; margin: 22px; margin-bottom: -8px; margin-top: 6px;"
    ),
    
    
    
    
    #delincuencia ----
    caja_app(titulo = "Delincuencia en Chile",
             texto = div(
               markdown("Visualización de **estadísticas oficiales de delincuencia**, separadas por comuna y delito, para darle contexto y seriedad a un tema país a partir de datos objetivos."),
              markdown("Selecciona una comuna y luego uno o varios delitos para obtener un gráfico de líneas que muestra una **serie de tiempo** de la cantidad de delitos, desde 2010 hasta 2023. Además, puedes visualizar la **cantidad de delitos por año** en la comuna seleccionada, el promedio de delitos en los gobiernos recientes, y una visualización de los tres **delitos más frecuentes** en cada comuna.")),
             enlace = "https://bastianoleah.shinyapps.io/delincuencia_chile/",
             colores = colores$delincuencia,
             imagen = "www/delincuencia_chile.png", estilo_imagen = "height: 150px;  margin: 22px; margin-top: 8px;"
    ),
    
    
    
    
    #corrupción ----
    tags$a(style = "text-decoration: none !important;",
      div(class = "icono", style = estilar_cajas(colores$corrupcion), 
          
          h3("Visualizador de casos de corrupción"),
          tags$img(src = "www/corrupcion_chile.png", style = "height: 140px;  margin-bottom: 6px; margin-top: 8px;"),
          # p(em("Próximamente..."), style = "opacity: .6; margin-top: 72px; margin-bottom: 72px;"),
          div(style = "text-align: left !important;",
              p("Catalogo y visualizador de los casos de corrupción más trascendentes del último tiempo en Chile, para poner en perspectiva los montos, responsables, y sectores políticos asociados."),
              p("Los datos son recopilados manualmente para producir una tabla con la mayor información posible sobre casos de corrupción, incluyendo responsables, delitos específicos, afiliación a partidos políticos, fundaciones involucradas y más, para alientar visualizaciones interactivas que permitan a la cuidadanía comprender de dónde viene la corrupción y cómo nos afecta como país.")
          )
      ),
      href = "https://bastianoleah.shinyapps.io/corrupcion_chile/", target = "_blank"),
    
    
    
    #femicidios ----
    tags$a(style = "text-decoration: none !important;",
      div(class = "icono", style = estilar_cajas(colores$femicidios), 
          
          h3("Femicidios en Chile"),
          tags$img(src = "www/femicidios_chile.png", style = "height: 140px;  margin-bottom: 20px; margin-top: 16px;"),
          
          div(style = "text-align: left !important;",
              p("Sitio con gráficos y tablas que expresan en cifras los datos de femicidios cometidos en Chile."),
              p("Estos datos, mantenidos por la Red Chilena contra la Violencia hacia las Mujeres, expresan la brutalidad manifestada de una sociedad patriarcal donde la violencia es una realidad transversal, llevada a su extremo en la agresión y asesinato de mujeres por razones de género.")
          )
      ),
      href = "https://bastianoleah.shinyapps.io/femicidios_chile/", target = "_blank"),
    
    
    
    
    #millonarios ----
    tags$a(style = "text-decoration: none !important;",
      div(class = "icono", style = estilar_cajas(colores$millonarios), 
          
          h3("Millonarios de Chile"),
          tags$img(src = "www/millonarios_chile.png", style = "height: 140px;  margin-bottom: 18px; margin-top: -8px;"),
          # p(em("Próximamente..."), style = "opacity: .6; margin-top: 72px; margin-bottom: 72px;"),
          div(style = "text-align: left !important;",
              p("Con este visualizador puedes poner en perspectiva las fortunas individuales más grandes del país, para así dimensionar un aspecto clave de la desigualdad en Chile y el mundo."),
              p("Diversas fuentes de datos permiten recopilar un listado de los empresarios más ricos de Chile. Distintas técnicas estadísticas y de visualización permiten dimensionar las enormes fortunas de estas personas, por ejemplo, comparando con los propios ingresos del usuario, o con los ingresos de toda la población del país.")
          )
      ),
      href = "https://bastianoleah.shinyapps.io/millonarios_chile/", target = "_blank"),
    
    
    #relacionador ----
    tags$a(style = "text-decoration: none !important;",
      div(class = "icono", style = estilar_cajas(colores$relacionador), 
          
          h3("Relacionador de variables"),
          tags$img(src = "www/relacionador_casen.png", style = "height: 150px; margin: 22px; margin-top: 15px;"),
          
          div(style = "text-align: left !important;",
              p("Visualizador que permite relacionar hasta 3 variables socioeconómicas en un gráfico de dispersión por comunas, para analizar la relación entre ellas."),
              p("Este visualizador permite", strong("experimentar correlaciones"), "con numerosas variables de temas como", strong("ingresos, educación, condiciones de vida, condiciones laborales, y más,"), "dado que permite utilizar libremente cualquiera de ellas como los ejes del gráfico, creando así visualizaciones personalizadas. Por ejemplo, se puede explorar si las comunas con bajo nivel educacional promedio son también las de menores ingresos, si es que las comunas con viviendas de menor calidad y menores ingresos se correlacionan con mayor hacinamiento o no, si las comunas de altos ingresos tienen menores afiliados a Fonasa, y más.")
          )
      ),
      href = "https://bastianoleah.shinyapps.io/casen_relacionador/", target = "_blank"),
    
    
    # mapas ----
    caja_app(titulo = "Comparador de mapas comunales",
             texto = div(
               p("Aplicación que reúne más de", strong("170 variables urbanísticas, sociales y económicas,"), "de nivel comunal, para todas las comunas del país, que permite al usuario elegir dos variables simultáneamente para compararlas visualmente por medio de", strong("dos mapas regionales.")),
               p("El visualizador entrega la posibilidad de poner a prueba relaciones entre variables tan distintas como áreas verdes y puntajes de pruebas de selección universitaria, nivel de ingresos y tasa de delitos, participación electoral y situación de las viviendas, etc., dejando al usuario la tarea de explicar los fenómenos que pueden surgir.")),
             enlace = "https://bastianoleah.shinyapps.io/comparador_mapas_chile/",
             colores = colores$comparador_mapas,
             imagen = "www/comparador_mapas_chile.png", estilo_imagen = "height: 150px; margin: 22px; margin-top: 6px;"
    ),
    
    
    
    #brechas de género ----
    tags$a(style = "text-decoration: none !important;",
      div(class = "icono",
          style = estilar_cajas(colores$brechas),
          
          h3("Brechas de género"),
          tags$img(src = "www/brechas_genero_casen.png", style = "height: 150px; margin: 17px; margin-top: 8px;"),
          div(style = "text-align: left !important;",
              p("Visualizador que detalla", strong("brechas de género en temas sociales, de vivienda e ingresos,"), "para analizar variables en las que las mujeres experimentan peores condiciones de vida, a nivel regional"),
              p("Selecciona una de las variables disponibles para generar un gráfico con todas las regiones del país, donde se detalla el", strong("porcentaje de la población femenina y masculina afectada"), "por la variable seleccionada, o si eliges variables de vivienda o familia, el", strong("porcentaje de hogares con jefatura femenina o masculina correspondientes."), "Los puntos del gráfico además se detallan con las", strong("brechas"), "o diferencias entre géneros existentes, volviendo explícitas las desigualdades o ausencia de las mismas.")
          )
      ),
      href = "https://bastianoleah.shinyapps.io/casen_brechas_genero/", target = "_blank"),
    
    
    #comparador ----
    tags$a(style = "text-decoration: none !important;",
      div(class = "icono", style = estilar_cajas(colores$comparador),
          
          h3("Comparador de ingresos"),
          tags$img(src = "www/comparador_casen.png", style = "height: 150px;  margin: 16px;"),
          
          div(style = "text-align: left !important;",
              p("Visualizador que compara", strong("distribuciones y promedios de ingresos"), "entre las comunas de Chile, para observar las diferencias en las realidades socioeconómicas del país."),
              p("Selecciona un grupo de comunas, y elige una variable de ingresos, como ingresos individuales, ingresos por hogar, ingresos per cápita o montos de pensiones/jubilación, para obtener un", strong("gráfico de densidad"), "que describe y compara las poblaciones de las comunas, y un gráfico de dispersión que ubica los ingresos de las comunas seleccionadas en comparación a todas las demás comunas del país.")
          )
      ),
      href = "https://bastianoleah.shinyapps.io/casen_comparador_ingresos/", target = "_blank"),
    
    
    
    #censo proyecciones ----
    tags$a(style = "text-decoration: none !important;",
      div(class = "icono", style = estilar_cajas(colores$censo),
          
          h3("Proyecciones de población del Censo"),
          tags$img(src = "www/censo_proyecciones.png", style = "height: 150px;  margin: 16px;"),
          
          div(style = "text-align: left !important;",
              p("Aplicación web que visualiza los datos oficiales del Instituto Nacional de Estadísticas de Chile sobre proyecciones de población; es decir, estimaciones del crecimiento poblacional hacia el futuro, a partir de los datos obtenidos en los censos oficiales."),
          )
      ),
      href = "https://bastianoleah.shinyapps.io/censo_proyecciones/", target = "_blank"),
    
    
    #cep ----
    caja_app(titulo = "Graficador encuesta CEP",
             texto = div(
               p("Aplicación web que permite visualizar gráficos de los resultados de las encuestas del Centro de Estudios Públicos."),
               p("Además, permite desagregar resultados en base a categorías sociodemográficas, filtrar grupos, configurar los gráficos y descargar los datos.")),
             enlace = "https://www.encuestacep.cl",
             colores = colores$cep,
             imagen = "www/graficador_cep.png", estilo_imagen = "height: 140px; margin-bottom: 20px; margin-top: 16px;",
             colores_claros = TRUE
    ) 
)
```


```{r otras}
#| echo: false
#| output: asis

div(style = "overflow-y: hidden; ",
    tags$style(paste(".anchorjs-link {display:none}")),
  
    
    h3("Otras utilidades", 
       style = css(color = color_texto, 
                   text_align = "center")),
    
    
    caja_app_chica(titulo = "Estimador de ingresos por hora",
                   texto = "Para trabajadores independientes o freelance: calcula un ingreso mensual promedio a partir de tu precio por hora, horas de trabajo diarias, y días de trabajo semanales.",
                   color = "#BC4F21",
                   enlace = "https://bastianoleah.shinyapps.io/estimador_ingresos_trabajo/"
    ),
    
    caja_app_chica(titulo = "Estimador de ingresos para clases particulares",
                   texto = "Para personas que hacen clases particulares: entrega una estimación de ingreso mensual y tiempo semanal de trabajo en base al precio de tus clases, cantidad de alumnos, y asistencia semanal de tus alumnos.",
                   color = "#1FBE9A",
                   enlace = "https://bastianoleah.shinyapps.io/estimador_ingresos_clases/"
    ),
    
    caja_app_chica(titulo = "Generador de ideas para dibujantes",
                   texto = "Para ilustradores, dibujantes y tatuadores: entrega ideas para dibujar de forma aleatoria, en base a decenas de parámetros, con opciones de personalización para controlar la complejidad y exageración de las ideas.",
                   color = "#c386f1",
                   enlace = "https://bastianoleah.shinyapps.io/autonatotattoo/"
    )
)
```



```{r footer}
#| echo: false
#| output: asis

#outro ----
div(
  fluidRow(
    column(12, 
           style = css(margin_top = "10px", font_size = "110%", 
                       color = color_texto,
                       margin_left = "30px", margin_right = "30px"),

           
markdown("Todas estas aplicaciones son de código abierto, y los [conjuntos de datos](https://bastianolea.github.io/datos_sociales/) son públicos. Cualquier persona puede utilizar [el código y los datos de las aplicaciones](https://github.com/bastianolea?tab=repositories) para adentrarse en el mundo del análisis de datos y [aprender a programar en R](https://bastianolea.rbind.io/blog/r_introduccion/)."),

           markdown("Todas estas apps han sido desarrolladas usando el [lenguaje de programación estadística y de código abierto R](https://www.r-project.org/about.html), 
                    bajo el paradigma de los paquetes [{tidyverse} para manipulación, limpieza y procesamiento de datos,](https://www.tidyverse.org) 
                    junto al [paquete {shiny} para desarrollar aplicaciones web interactivas.](https://shiny.posit.co)"),
           
           markdown("El código de las aplicaciones está disponible en sus respectivos 
             [repositorios GitHub](https://github.com/bastianolea?tab=repositories),
             incluendo todo el proceso de desarrollo, desde la descarga y limpieza de datos hasta el diseño de la interfaz de las apps."),

markdown("También tengo disponible un [repositorio de datos sociales](https://bastianolea.github.io/datos_sociales/) para que explores conjuntos de datos sociales listos para analizar."),
           
           markdown("¡Cualquier duda o comentario es bienvenido! Puedes encontrarme [en redes sociales](www.x.com/bastimapache) o [escribirme un correo](https://bastianolea.rbind.io/contact) con total libertad.")
           
    )
  ),
#   
#   # aviso ----
#   fluidRow(
#     column(12,
#                    cuadro_aviso(
#                      markdown("Si te interesa **aprender R** o **mejorar tus habilidades con R,** [contáctame!](https://bastianolea.rbind.io/contact) Ofrezco **clases particulares de R,** asesorías, y apoyo para cualquier tipo de proyecto."),
# 
#                      div(style = css(font_size = "80%", color = lighten(color_enlaces, 0.2), opacity = "100%"),
#                      markdown("
#                               - Aprende a usar R desde cero con clases personalizadas a tu nivel y objetivos
#                               - Resuelve tus dudas y soluciona las dificultades que tengas con tu proyecto de R
#                               - Visualiza datos de forma atractiva y crea bellas tablas con R
#                               - Automatiza tus procesos con R
#                               - Genera reportes automatizados con R
#                               - Aprende a desarrollar apps interactivas con R Shiny
#                               ")),
# markdown("
#                               También puedo desarrollar aplicaciones Shiny personalizadas y de acuerdo a tus necesidades, y más!"),
#                    )
#     )
#   ),
  

  fluidRow(
    column(12, 
           style = css(margin_top = "40px", font_size = "90%", 
                       color = color_texto,
                       margin_left = "30px", margin_right = "30px;"),
           
           markdown("_Bastián Olea Herrera._ Magíster en sociología, analista de datos."),
           
           markdown("[baolea@uc.cl](https://bastianolea.rbind.io/contact)"), 
           
           markdown("[bastianolea.rbind.io](https://bastianolea.rbind.io)"),
           br()
    )
  ),

# cafecito ----
fluidRow(
  column(12, style = "max-width: 360px; margin: auto;",
         
         tags$style(HTML(".cafecito:hover {opacity: 75%; transition: 0.3s; color: black !important;}
                         .cafecito a:hover {color: black}")),
         
         tags$style(HTML(".bmc-btn-text {color:", color_fondo, "!important;}")),
         
         div(class = "cafecito",
             style = "transform:scale(0.7);",
           tags$body(HTML('<script type="text/javascript" src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js" data-name="bmc-button" data-slug="bastimapache" data-color="#FFDD00" data-emoji=""  data-font="Bree" data-text="Regálame un cafecito" data-outline-color="#000000" data-font-color="#000000" data-coffee-color="#ffffff" ></script>'))
         )
         
  )
)

)
```

